version: "3"

services:
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        restart: always
        command: redis-server --save 60 1 --loglevel warning
    backend:
        build: .
        container_name : todobackend
        command: > 
            sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:9000 &&
                   celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
        volumes:
            - ./core:/app
        ports:
            - "9000:9000"
        environment:
            - SECRET_KEY=22
            - DEBUG=True
        depends_on:
            - redis
    worker:
        build: .
        command: celery -A core worker --loglevel INFO
        volumes:
            - ./core:/app
        depends_on:
            - redis
            - backend

    smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
          - '5000:80'
          - '25:25'
          - '143:143'
        volumes:
            - smtp4dev-data:/smtp4dev
        environment:
          - ServerOptions__HostName=smtp4dev
    postgres-db:
        image: postgres:13-alpine
        container_name: postgres-db
        environment:
          - POSTGRES_DB=todo-db
          - POSTGRES_USER=alimm
          - POSTGRES_PASSWORD=DjangoBackend
        ports:
          - "5432:5432"
        volumes:
            - postgres-volume:/var/lib/postgresql/data
            
volumes:
  smtp4dev-data:
