name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup docker compose
      run: ducker-compose up -t
    - name: run test for pytest config
      run: docker exec training-backend sh-c "pytest ."
