name: Django TODO project test for api blogs and accounting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup docker compose
      run: docker-compose -f docker-compose-stage.yml up -d
    - name: run test for pytest config
      run: docker exec todobackend sh -c "pytest && flake8 ."

  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    name: Deploy 
    needs: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ssh to vps ubuntu
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST_VPS}}
        port: ${{secrets.PORT}}
        script: |
          cd ${{secrets.PATH_GITHUB}} 
          docker-compose -f docker-compose-stage.yml stop
          git pull
          docker-compose -f docker-compose-stage.yml start
